/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WritingIndexRouteImport } from './routes/writing/index'
import { Route as SoftwareIndexRouteImport } from './routes/software/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as SoftwarePixelSvgIndexRouteImport } from './routes/software/pixel-svg/index'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingIndexRoute = WritingIndexRouteImport.update({
  id: '/writing/',
  path: '/writing/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareIndexRoute = SoftwareIndexRouteImport.update({
  id: '/software/',
  path: '/software/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwarePixelSvgIndexRoute = SoftwarePixelSvgIndexRouteImport.update({
  id: '/software/pixel-svg/',
  path: '/software/pixel-svg/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/projects': typeof ProjectsRoute
  '/games': typeof GamesIndexRoute
  '/software': typeof SoftwareIndexRoute
  '/writing': typeof WritingIndexRoute
  '/software/pixel-svg': typeof SoftwarePixelSvgIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/projects': typeof ProjectsRoute
  '/games': typeof GamesIndexRoute
  '/software': typeof SoftwareIndexRoute
  '/writing': typeof WritingIndexRoute
  '/software/pixel-svg': typeof SoftwarePixelSvgIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/projects': typeof ProjectsRoute
  '/games/': typeof GamesIndexRoute
  '/software/': typeof SoftwareIndexRoute
  '/writing/': typeof WritingIndexRoute
  '/software/pixel-svg/': typeof SoftwarePixelSvgIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/projects'
    | '/games'
    | '/software'
    | '/writing'
    | '/software/pixel-svg'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/projects'
    | '/games'
    | '/software'
    | '/writing'
    | '/software/pixel-svg'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/projects'
    | '/games/'
    | '/software/'
    | '/writing/'
    | '/software/pixel-svg/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ProjectsRoute: typeof ProjectsRoute
  GamesIndexRoute: typeof GamesIndexRoute
  SoftwareIndexRoute: typeof SoftwareIndexRoute
  WritingIndexRoute: typeof WritingIndexRoute
  SoftwarePixelSvgIndexRoute: typeof SoftwarePixelSvgIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/': {
      id: '/writing/'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof WritingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software/': {
      id: '/software/'
      path: '/software'
      fullPath: '/software'
      preLoaderRoute: typeof SoftwareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software/pixel-svg/': {
      id: '/software/pixel-svg/'
      path: '/software/pixel-svg'
      fullPath: '/software/pixel-svg'
      preLoaderRoute: typeof SoftwarePixelSvgIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ProjectsRoute: ProjectsRoute,
  GamesIndexRoute: GamesIndexRoute,
  SoftwareIndexRoute: SoftwareIndexRoute,
  WritingIndexRoute: WritingIndexRoute,
  SoftwarePixelSvgIndexRoute: SoftwarePixelSvgIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
